# Generated by Django 5.1.4 on 2024-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_text_blog_content_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Blog Post', max_length=240),
        ),
    ]
