# Generated by Django 5.1.4 on 2024-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_profile_photo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='photos/no-profile-photo.png', null=True, upload_to='photos/'),
        ),
    ]
